### ISSUE TITLE
Can you release the source code of the demo please?

### ISSUE THREAD

**Issue by cjlaborde** [fuxingloh/vue-horizontal-list#10]
I would like to use these as templates.
https://nuxt-app.now.sh/vue-horizontal-list
would make things easier to understand.

You could perhaps make new branch or add a demo folder.

**Comment by fuxingloh** [comment]
Sorry, my bad it's in this repo: https://github.com/fuxingloh/nuxt-app/blob/master/components/examples/ExampleHorizontalList.vue

I will move it into this repo in the future.
