### ISSUE TITLE
Bug with Rendering incorrectly

### ISSUE THREAD

**Issue by cjlaborde** [fuxingloh/vue-horizontal-list#12]
https://gifyu.com/image/nBk0
As you can see from Gif image of the error.
Position Starts at 0 which is correct.

Yet when the page is loaded is not showing the first item instead is showing 4th item.
So is rendering the incorrect slide.

Is there a way to force this or can you fix it?

Basically I have an array on 8 items which is ordered correctly

Yet When I load the page is rendering the item
 4 6 7 8
Instead of correctly rendering items
0 1 2 3

As you can see as well 
_hasNext:true
_hasPrev:false
_itemWidth:268
and position are correct
Yet they don't align with what is displayed.

The Snow cabin Should be the First Item displayed not the 4 item in the array.
This is the code
```js
     <vue-horizontal-list :items="reserved"
                                     :options="{responsive: [{end: 576, size: 1}, {start: 576, end: 768, size: 2},{start: 768, end: 992, size: 3},{size: 4}]}">
                    <template v-slot:default="{item}">
                        <div>
                            <div class="aspect r-5-3 border-3 overflow-hidden">
                                <img :src="item.first_medium_image"/>
                            </div>
                            <div class="mt-8 flex-between">
                                <div class="small-bold">BEST</div>
                                <div class="small-bold">3/5</div>
                            </div>

                            <h6>{{item.listing_name}}</h6>
                            <p class="mt-4"><b>$200 USD</b> / night</p>
                        </div>
                    </template>
                </vue-horizontal-list>

```

**Comment by fuxingloh** [comment]
Hey, thanks for the comment.

I tried replicating this issue on my demo and dev environment but I was unable to reproduce this. From my little experience dealing with web, I believe this may be a CSS issue. You could try inspecting the CSS inheritance it might be conflicting with the `vue-horizontal-list`.

Or is it possible to provide more information surrounding this implementation?

**Comment by cjlaborde** [comment]
I found class that is causing the issue.
https://i.imgur.com/7rtQPoh.png
vhl-list
As you see the starting in the end of the scroll instead of the start.

**Comment by cjlaborde** [comment]
@fuxingloh going to close this issue seems to be on my end.
I can't figure out why it is happening.
1) None working: getting data from an axios get request.
2) Working:  Getting data from Prop.
Both Data exactly the same and same css classes.
So going to switch it to props.

**Comment by mauricoder** [comment]
I'm having exactly the same issue with **vue-horizontal-list 1.0.11**

With data loaded from axios the lists is rendered in the last slide instead of the first one.

With data taken from props the list is rendered OK. I'm switching to props.

**Comment by cjlaborde** [comment]
> I'm having exactly the same issue with **vue-horizontal-list 1.0.11**
> 
> With data loaded from axios the lists is rendered in the last slide instead of the first one.
> 
> With data taken from props the list is rendered OK. I'm switching to props.

Are you using Laravel by the way?
