### ISSUE TITLE
Move examples to within the same repo

### ISSUE THREAD

**Issue by fuxingloh** [fuxingloh/vue-horizontal-list#13]
Currently the demo is housed in `fuxingloh/nuxt-app` which uses confusing 3rd party css classes to create the examples. Ideally the examples should be:
- [ ] self contained with 0 dependencies 
- [ ] easy to follow with it's own live hosting
- [ ] native css without using any framework or library

**Comment by cjlaborde** [comment]
This would great addition since I don't use less and found it confusing. Neither use Sass using postcss currently. Better have native css.
