### ISSUE TITLE
Navigation controls are not updated to reflect position when user scroll it with their trackpad

### ISSUE THREAD

**Issue by fuxingloh** [fuxingloh/vue-horizontal-list#14]
Left Right Navigation should reflect the real position after scroll snap event.

This unique scenario can only be experienced with a computer that support horizontal scrolling (a.k.a a trackpad).

**Comment by Draccano** [comment]
The solution could be setup listener for [dragging ](https://www.w3schools.com/html/html5_draganddrop.asp) the list and after dragend, evaluate the new position that is the smallest left value between item and left corner (via getBoundingClientRect).

**Comment by Draccano** [comment]
@fuxingloh I have solved this problem. In scroll container of the vue-horizontal-list component, I setup @touchend listener, that evaluates actual position of the shown item. It works like a charm. Should I make PR ?

**Comment by fuxingloh** [comment]
@Draccano please do, appreciate it!

**Comment by Draccano** [comment]
@fuxingloh I just made PR https://github.com/fuxingloh/vue-horizontal-list/pull/29
