### ISSUE TITLE
Nuxt props error

### ISSUE THREAD

**Issue by topninja** [fuxingloh/vue-horizontal-list#26]
![image](https://user-images.githubusercontent.com/47001971/88672168-282e4380-d0b5-11ea-990a-0d53658115ae.png)

this vue-horizontal-list is working well on simple object props.
but json object error occurs on which pass some big object.

**Comment by fuxingloh** [comment]
Hi, could you provide more information on how to reproduce this anomaly? 
E.g. The JSON structure, object size and etc.
Thanks!

**Comment by topninja** [comment]
Thanks for your reply...
I think this issue is from this string value.
![image](https://user-images.githubusercontent.com/47001971/88677659-90802380-d0bb-11ea-9e34-f1f9d04d54db.png)

**Comment by fuxingloh** [comment]
I am sorry, I don't think I can do anything to help you with this as I believe this is a vue/js restriction.

However, if the error is as described, you could map it into another JSON structure without the circular structure before injecting into any vue component as props.

**Comment by topninja** [comment]
Thanks.
