### ISSUE TITLE
[Feature Request] mouse drag support

### ISSUE THREAD

**Issue by AbdallahAlhaddad** [fuxingloh/vue-horizontal-list#27]
It would be very useful if we want to hide arrows when the browser page width is low, so the client can scroll using the mouse instead.

**Comment by Draccano** [comment]
You are right, this feature could improve the user feeling,  I’ll look closer to the solution in a free time. 😊

**Comment by Draccano** [comment]
As promised, https://github.com/fuxingloh/vue-horizontal-list/pull/52/files

**Comment by AbdallahAlhaddad** [comment]
Thank you for your effort. 😄
