### ISSUE TITLE
How to wrap vue-horizontal-list in Nuxt?

### ISSUE THREAD

**Issue by lmuzquiz** [fuxingloh/vue-horizontal-list#5]
How to wrap vue-horizontal-list in Nuxt?

**Comment by fuxingloh** [comment]
https://github.com/fuxingloh/nuxt-app/blob/master/components/examples/ExampleHorizontalList.vue

**Comment by guastallaigor** [comment]
Hello @fuxingloh.
The provided example (https://github.com/fuxingloh/nuxt-app/blob/master/components/examples/ExampleHorizontalList.vue) is not Nuxt SSR. 
You are using mode 'spa' there.
Could you please tell me how to use vue-horizontal-list with SSR support, without getting this error?

![image](https://user-images.githubusercontent.com/22016005/86424610-65bbce80-bcb9-11ea-91f3-e19228319416.png)

Thank you.

**Comment by fuxingloh** [comment]
@guastallaigor https://github.com/fuxingloh/vue-horizontal-list/pull/21 v1.0.11 should fix it. 

> I added smoothscroll feature due to lack of feature support in safari. However it caused a regression error making SSR break.

I will better address with in the future, thanks for highlighting.
