### ISSUE TITLE
TypeError: Cannot read property 'scrollTo' of undefined Error on autoplay like a component using vue-router

### ISSUE THREAD

**Issue by joseortiz9** [fuxingloh/vue-horizontal-list#55]
I have an app consisting of several top-level components. These are loaded by vue-router when the appropriate route is specified in the URI. You can think of this as a simple SPA.
I implemented the vue-horizontal-list component in the landing site with the autoplay functionality. Everything works fine on the first page, and after refresh (F5), but later when I navigate to the different views I'm getting the next error: 
```
vue-horizontal-list.esm.js?6336:740 
Uncaught TypeError: Cannot read property 'scrollTo' of undefined
    at VueComponent.go (vue-horizontal-list.esm.js?6336:740)
    at VueComponent.eval (vue-horizontal-list.esm.js?6336:757)
```
Analyzing the code seems that the list of children in the carousel is getting undefined after making the router view change, but I don't get why the animation and movement happen anyway...
https://github.com/fuxingloh/vue-horizontal-list/blob/aebf7fe91e6df3dab69d5650330b8063b8aa6ab1/src/vue-horizontal-list.vue#L317
https://github.com/fuxingloh/vue-horizontal-list/blob/aebf7fe91e6df3dab69d5650330b8063b8aa6ab1/src/vue-horizontal-list.vue#L304

My components are being lazy-loaded by the router. And this only happens after navigating with this, when I make the refresh these errors stop. 
With the autoplay happens every time that the card is moved to the next, but the functionality happens! the problem is that after 5 mins I finish with hundreds of these errors. 
Here is my code to reproduce it.
```vue
<vue-horizontal-list
          :items="brands"
          :options="{
            autoplay: { play: true, repeat: true, speed: 5000 }
          }"
        >
          <template v-slot:default="{ item }">
            <div class="item">
              <b-card
                img-src="../assets/categories/category1.jpeg"
                img-alt="category1" :data-label="item.id" img-top align="center" class="shadow rounded"
              >
                <default-button icon-name="cart4" :onClick="goToShop" />
              </b-card>
            </div>
          </template>
        </vue-horizontal-list>
```

**Comment by Draccano** [comment]
I use the component in SPA as well without any problem in case of navigation. Please check, whether are data appropietaly binded to the vue-horizontal-list after refresh, because it looks there doesn’t exist reference to the list with items. Could you create sandbox example?

**Comment by joseortiz9** [comment]
I don't know how they can get undefined if they are simple vue-bootstrap components, and in my example, the app use fake data just to test the functionality, but with images, without it, with simple components or bootstrap one it still happens. Here is how looks the data in my Homecomponent
```vue
data() {
    return {
      brands: [
        { id: 1, title: "Lacteos" },
        { id: 2, title: "Gaseosas" },
        { id: 3, title: "Perros" },
        ......
      ],
```

**Comment by Draccano** [comment]
I don't have experience with vue-bootstrap but I guess that lib doesn't cause the problem. However, it is hard to find the solution in case I don't have the working example. Try to implement these usecases https://fuxingloh.github.io/vue-horizontal-list/ in your spa.

**Comment by joseortiz9** [comment]
I have it here actually.
https://github.com/joseortiz9/supermarkets1a-landing
Hope you can find what is going on, I had hoped for this library. And I already tried with many of them(use cases), as I said it happens every time item is changed, like move to the next one, but only after navigating through the spa. Is weird...

**Comment by Draccano** [comment]
I have found problem, as described it is due to setInterval callback for nonexisting list. 
`beforeDestroy() {
       if (this.autoPlayInterval) {
            clearInterval(this.autoPlayInterval);
       }
},`
I just made PR in your repo, it is working. In meantime I will make PR fix in vue-horizontal-list component. Thank you for the info.
