### ISSUE TITLE
Navigation by a certain number of items

### ISSUE THREAD

**Issue by joseortiz9** [fuxingloh/vue-horizontal-list#58]
I have been trying to make this functionality in the library but I still can not, and my code is a shame to make a PR, can u implement it? 
The navigation for every kind of list happens by a big amount of elements, maybe is possible to make an option that says by how many items you want to go forward or back.
Thanks!!!

**Comment by fuxingloh** [comment]
I have created another library for such a use case you can check it out [here](https://vue-horizontal.fuxing.dev/). It should cover all the requirements you need and it's SSR/SSG end to end tested so you can trust it works as expected on all browsers.

* [Scroll displacement to control the amount of width to move on prev/next with auto snapping.](https://vue-horizontal.fuxing.dev/features#displacement)
* [Scroll to index](https://vue-horizontal.fuxing.dev/features#scrolltoindex)
* [Another example](https://vue-horizontal.fuxing.dev/recipes/square#album)

**Comment by joseortiz9** [comment]
sad you didn't continue with this one, gotta give it a try to the other one, seems pretty fancy!
