### ISSUE TITLE
How to use it in CDN Global mode?

### ISSUE THREAD

**Issue by amchconsult** [fuxingloh/vue-horizontal-list#8]
How to use it in CDN Global mode?

I have found the CDN but it give the error:
vue-horizontal-list.min.js:1 Uncaught ReferenceError: smoothscroll is not defined
    at vue-horizontal-list.min.js:1

Please can you give an example.
Thank you

**Comment by fuxingloh** [comment]
I am not very sure what you mean. What is CDN Global mode?

I am using nuxt with it hosted on vercel.com CDN.

https://github.com/fuxingloh/nuxt-app/blob/master/components/examples/ExampleHorizontalList.vue

**Comment by amchconsult** [comment]
I have found 
https://www.jsdelivr.com/package/npm/vue-horizontal-list

the library is great.

I am trying to use it in html vue as global

**Comment by fuxingloh** [comment]
Hi, I am not very experience with using jsdelivr. However since the error specified that smoothscroll is required, maybe you can try adding it.
https://www.jsdelivr.com/package/npm/smoothscroll

**Comment by amchconsult** [comment]
I have try but it still not working.
Can you do an example of how to use it in html as global?
thank you very much

**Comment by fuxingloh** [comment]
Hello, I recently published another project called [Vue Horizontal](https://github.com/fuxingloh/vue-horizontal) and one of requirements was to make it work for CDN Global mode. I have taken into account of everything I know about modern web dev, cross-browser testing and support, SSG/SSR and more of those fun web dev things.

You can check it out here https://vue-horizontal.fuxing.dev/installation/#install-script, the project is here: https://github.com/fuxingloh/vue-horizontal

#### Made simple:
```html
<vue-horizontal>
  <div class="item">
    <p>Can be just any HTML declaration</p>
  </div>
  <section v-for="i in [0,1]" :key="i">
    <h3>{{ i }}: v-for works tooo!</h3>
  </section>
</vue-horizontal>

<script src="https://unpkg.com/vue"></script>
<script src="https://unpkg.com/vue-horizontal"></script>
<script>
new Vue({ el: "#app" });
</script>
```

I am going to close this now!

**Comment by amchconsult** [comment]
thank you
