### ISSUE TITLE
Scroll inside of each section

### ISSUE THREAD

**Issue by guastallaigor** [fuxingloh/vue-horizontal-list#9]
Hello,

Great project! I would like to know if right now there's a way to put a lot of text inside of it, and remove the CSS attributes `overflow: hidden;` , `text-overflow: ellipsis;` , `word-break: break-word;` and maybe adding a `height` to it.

Basic example **(see the first one only, I changed the HTML in the demo)**:

![image](https://user-images.githubusercontent.com/22016005/81607936-daeedf80-93ab-11ea-8eae-f21a09e46cac.png)

Thank you.

**Comment by fuxingloh** [comment]
The CSS attributes is added by you based on your design requirement, you can add any attribute to it based on your requirement and the component will adapt to it.

![image](https://user-images.githubusercontent.com/4266087/81627016-c48a6780-942f-11ea-873a-e8a8b98f1f62.png)

**Comment by guastallaigor** [comment]
Got it, thank you again
